Repository NightFyre/Palworld-Internal, pull requests merged in 2024-02, with the labels that each got.

#17 [XBOX] Update Rendering Functionality
  include/Menu.hpp
  include/config.h
  include/feature.h
  include/initialize.hpp
  src/Menu.cpp
  src/config.cpp
  src/feature.cpp
Labels: XBOX

#16 [SteamDeck] Update Rendering Functionality
  include/Menu.hpp
  include/config.h
  include/feature.h
  include/initialize.hpp
  src/Menu.cpp
  src/config.cpp
  src/feature.cpp
Labels: SteamDeck

#18 [STEAM] Optimize GWorld Runner
  dllmain.cpp
  include/Console.hpp
  include/D3D11Window.hpp
  include/Game.hpp
  include/Hooking.hpp
  include/Menu.hpp
  include/config.h
  include/initialize.hpp
  src/Console.cpp
  src/D3D11Window.cpp
  src/Game.cpp
  src/Hooking.cpp
  src/Menu.cpp
  src/config.cpp
Labels: STEAM

#19 [SteamDeck] Optimize GWorld Runner
  dllmain.cpp
  include/Console.hpp
  include/D3D11Window.hpp
  include/Game.hpp
  include/Hooking.hpp
  include/Menu.hpp
  include/config.h
  include/initialize.hpp
  src/Console.cpp
  src/D3D11Window.cpp
  src/Game.cpp
  src/Hooking.cpp
  src/Menu.cpp
  src/config.cpp
Labels: SteamDeck

#20 [XBOX] Optimize GWorld Runner
  dllmain.cpp
  include/Console.hpp
  include/D3D11Window.hpp
  include/Game.hpp
  include/Hooking.hpp
  include/Menu.hpp
  include/config.h
  include/initialize.hpp
  src/Console.cpp
  src/D3D11Window.cpp
  src/Game.cpp
  src/Hooking.cpp
  src/Menu.cpp
  src/config.cpp
Labels: XBOX

#22 Speedhack changes and fix infinite stamina for pals
  DX11-Base.vcxproj
  dllmain.cpp
  include/config.h
  include/feature.h
  src/Menu.cpp
  src/feature.cpp
Labels: enhancement
